version: "1.0"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    hostname: 'sqlserver'
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: NHZp0CDKWZF1
      MSSQL_PID: Developer
      MSSQL_COLLATION: LATIN1_GENERAL_100_CI_AS_SC_UTF8
    ports:
      - '1444:1433'
    volumes:
      - db_data:/var/opt/mssql
  bot:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./:/opt/app/
      - ./config.json:/etc/app/config.json
    restart: always
    stdin_open: true
    links:
      - db
    tty: true
    command: python -m main

volumes:
  db_data: